### PR TITLE
Update for SMAPI 2.0

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request...

* Fixes compatibility with SMAPI 2.0 (without breaking compatibility with earlier versions).
* Updates the [mod build package](https://github.com/Pathoschild/Stardew.ModBuildConfig) to the latest version.  
    _This adds support for deploying into the mod folder automatically, which I enabled for BuyRecipes. I left SendItems's deploy task as-is due to its config handling._
* Replaces custom update checks with SMAPI's new update-check feature.
* Bumps the versions for release.

I branched from `master` so the updates can be deployed independently of your refactor in `develop`. If the changes look fine, can you release [BuyRecipes 1.0.1.zip](https://github.com/Denifia/StardewMods/files/1354411/BuyRecipes.1.0.1.zip) and [SendItems 1.0.3.zip](https://github.com/Denifia/StardewMods/files/1354412/SendItems.1.0.3.zip)? (Once this pull request is accepted, I can merge the changes into your `develop` branch if you want.)

### CODE REVIEW

**Comment by Denifia** [comment]
Out of interest... was this update requested by someone in the community, or you're just updating a bunch anyway?

**Comment by Pathoschild** [comment]
I'm updating a lot of mods as part of the [SMAPI 2.0 migration](https://stardewvalleywiki.com/Modding:Updating_mods_for_SMAPI_2.0). Some players may have requested the update, but unfortunately I don't keep track beyond making sure the requested mods are on that list.

**Comment by Pathoschild** [comment]
Thanks for the review! You sent me an invite to the repo; did you want me to merge this pull request?

**Comment by Denifia** [comment]
I'm not in a position where I can push out a new build for at least a week. Yup, I've given you access so if you'd like to merge and create a new build - feel free :)

Also, this way if in the future you want to make changes so support SMAPI, you can just jump in a do it :P

**Comment by Pathoschild** [comment]
Will do!

If you add me as a team member on the Nexus mod pages, I can release the updates too. Here's how if you're interested:
1. Open the mod pages (see [Buy Cooking Recipes](https://www.nexusmods.com/stardewvalley/mods/1126) and [Send Items](https://www.nexusmods.com/stardewvalley/mods/1087)).
2. Click _edit attributes_ in the sidebar.
3. Add `Pathoschild` under _Other team members_ and click the `(+)` button next to the field.
4. Click _submit_ at the bottom.

**Comment by Denifia** [comment]
Coolies... I've added you to both projects on Nexus mods. Feel free to update the mods, release new versions, etc.

**Pull request merged**
